//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.View.NhanVien.Admin {
    
    
    public partial class CUD {
        
        /// <summary>
        /// CUDForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.NhanVien.Form._Form CUDForm;
        
        /// <summary>
        /// pnlExtraInforamtion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlExtraInforamtion;
        
        /// <summary>
        /// btLamViecNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btLamViecNew;
        
        /// <summary>
        /// LVRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.LamViec.Form._LVRadGrid LVRadGrid;
        
        /// <summary>
        /// btCTXHNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btCTXHNew;
        
        /// <summary>
        /// CTXHRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.ThamGiaCTXH.Form._TGCTXHRadGrid CTXHRadGrid;
        
        /// <summary>
        /// btDaoTaoNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btDaoTaoNew;
        
        /// <summary>
        /// DTRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.QuaTrinhDaoTao.Form._QTDTRadGrid DTRadGrid;
        
        /// <summary>
        /// btQuanHeNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btQuanHeNew;
        
        /// <summary>
        /// QHRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.QuanHe.Form._QuanHeRadGrid QHRadGrid;
        
        /// <summary>
        /// btNgoaiNguNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btNgoaiNguNew;
        
        /// <summary>
        /// TDNNRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.TrinhDoNgoaiNgu.Form._TDNNRadGrid TDNNRadGrid;
        
        /// <summary>
        /// btTinHocNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btTinHocNew;
        
        /// <summary>
        /// TDTHRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.TrinhDoTinHoc.Form._TDTHRadGrid TDTHRadGrid;
        
        /// <summary>
        /// btDanhHieuNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btDanhHieuNew;
        
        /// <summary>
        /// PTDHRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.PhongTangDanhHieu.Form._PTDHRadGrid PTDHRadGrid;
        
        /// <summary>
        /// btKhenThuongNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btKhenThuongNew;
        
        /// <summary>
        /// KTRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.KhenThuong.Form._KTRadGrid KTRadGrid;
        
        /// <summary>
        /// btKyLuatNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btKyLuatNew;
        
        /// <summary>
        /// KLRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.KyLuat.Form._KLRadGrid KLRadGrid;
        
        /// <summary>
        /// btDanhGiaNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btDanhGiaNew;
        
        /// <summary>
        /// DGRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.DanhGia.Form._DGRadGrid DGRadGrid;
        
        /// <summary>
        /// btChinhSachNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btChinhSachNew;
        
        /// <summary>
        /// CSRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.ChinhSach.Form._CSRadGrid CSRadGrid;
        
        /// <summary>
        /// btKeKhaiNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btKeKhaiNew;
        
        /// <summary>
        /// KKRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.KeKhai.Form._KKRadGrid KKRadGrid;
        
        /// <summary>
        /// btDanhGiaLaoDongNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btDanhGiaLaoDongNew;
        
        /// <summary>
        /// DGLDRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.DanhGiaLaoDong.Form._DGLDRadGrid DGLDRadGrid;
        
        /// <summary>
        /// btDanhGiaVienChucNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btDanhGiaVienChucNew;
        
        /// <summary>
        /// DGVCRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.DanhGiaVienChuc.Form._DGVCRadGrid DGVCRadGrid;
        
        /// <summary>
        /// btDanhGiaDangVienNew control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btDanhGiaDangVienNew;
        
        /// <summary>
        /// DGDVRadGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLyNhanSu.View.DanhGiaDangVien.Form._DGDVRadGrid DGDVRadGrid;
    }
}
