//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.PhuTrachChamCongs = new HashSet<PhuTrachChamCong>();
        }
    
        public int ACCID { get; set; }
        public string ACCEmail { get; set; }
        public string ACCPassword { get; set; }
        public int ACCChucNang { get; set; }
        public bool ACCStatus { get; set; }
        public bool ACCUpThongTinCaNhan { get; set; }
        public bool ACCUpLyLich { get; set; }
        public bool ACCInLyLich { get; set; }
        public bool ACCInKeKhai { get; set; }
        public bool ACCUpKeKhai { get; set; }
        public bool ACCInDanhGia { get; set; }
        public bool ACCUpDanhGia { get; set; }
        public int NVID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhuTrachChamCong> PhuTrachChamCongs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
