//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public int CCID { get; set; }
        public int LVID { get; set; }
        public System.DateTime CCDATE { get; set; }
        public int LCCID { get; set; }
    
        public virtual LoaiChamCong LoaiChamCong { get; set; }
        public virtual LamViec LamViec { get; set; }
    }
}
