//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChinhTriXaHois
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChinhTriXaHois()
        {
            this.ThamGiaChinhTriXaHois = new HashSet<ThamGiaChinhTriXaHois>();
        }
    
        public int CTXHID { get; set; }
        public string CTXHTen { get; set; }
        public string CTXHDiaChi { get; set; }
        public string CTXHDienThoai { get; set; }
        public string CTXHFax { get; set; }
        public string CTXHEmail { get; set; }
        public string CTXHWebsite { get; set; }
        public string CTXHGioiThieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThamGiaChinhTriXaHois> ThamGiaChinhTriXaHois { get; set; }
    }
}
