//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaDangVien
    {
        public int DGDVID { get; set; }
        public string DGDVChucVuDang { get; set; }
        public string DGDVChucVuChinhQuyen { get; set; }
        public string DGDVDonVi { get; set; }
        public string DGDVChiBo { get; set; }
        public string DGDVHangChucDanh { get; set; }
        public int DGDVBac { get; set; }
        public decimal DGDVHeSoLuong { get; set; }
        public string DGDVUuDiem { get; set; }
        public string DGDVKetQuaKhacPhuc { get; set; }
        public string DGDVKhuyetDiem { get; set; }
        public string DGDVPhuongHuong { get; set; }
        public string DGDVDanhGia { get; set; }
        public int DGDVNam { get; set; }
        public System.DateTime DGDVNgayThang { get; set; }
        public int NVID { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
