//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaLaoDong
    {
        public int DGLDID { get; set; }
        public int DGLDNam { get; set; }
        public string DGLDChucDanh { get; set; }
        public string DGLDDonVi { get; set; }
        public string DGLDNgheNghiep { get; set; }
        public int DGLDBac { get; set; }
        public decimal DGLDHeSoLuong { get; set; }
        public string DGLDKetQua { get; set; }
        public string DGLDDaoDuc { get; set; }
        public string DGLDTrachNhiem { get; set; }
        public string DGLDNghiaVu { get; set; }
        public string DGLDUuDiem { get; set; }
        public string DGLDPhanLoai { get; set; }
        public string DGLDYKien { get; set; }
        public string DGLDThongNhat { get; set; }
        public System.DateTime DGLDNgay { get; set; }
        public int NVID { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
