//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dat
    {
        public int DATID { get; set; }
        public string DATDiaChi { get; set; }
        public double DATDienTich { get; set; }
        public long DATGiaTri { get; set; }
        public string DATQuyenSoHuu { get; set; }
        public string DATGhiChu { get; set; }
        public int KKID { get; set; }
    
        public virtual KeKhai KeKhai { get; set; }
    }
}
