//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonVi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonVi()
        {
            this.DonVis1 = new HashSet<DonVi>();
            this.PhuTrachChamCongs = new HashSet<PhuTrachChamCong>();
            this.LamViecs = new HashSet<LamViec>();
        }
    
        public int DVID { get; set; }
        public string DVTen { get; set; }
        public Nullable<int> DVTrucThuocID { get; set; }
        public bool DVTrangThai { get; set; }
        public string DVNoiDung { get; set; }
        public Nullable<int> DVBienChe { get; set; }
        public string DVSDT { get; set; }
        public string DVDiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonVi> DonVis1 { get; set; }
        public virtual DonVi DonVi1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhuTrachChamCong> PhuTrachChamCongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LamViec> LamViecs { get; set; }
    }
}
