//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaiTrinh
    {
        public int GTID { get; set; }
        public decimal GTSoLuong { get; set; }
        public bool GTIsTang { get; set; }
        public string GTNoiDung { get; set; }
        public int KKID { get; set; }
        public int LGTID { get; set; }
    
        public virtual KeKhai KeKhai { get; set; }
        public virtual LoaiGiaiTrinh LoaiGiaiTrinh { get; set; }
    }
}
