//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeKhai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KeKhai()
        {
            this.Nhas = new HashSet<Nha>();
            this.KeKhaiCons = new HashSet<KeKhaiCon>();
            this.Dats = new HashSet<Dat>();
            this.Tiens = new HashSet<Tien>();
            this.DongSans = new HashSet<DongSan>();
            this.DaQuis = new HashSet<DaQui>();
            this.TaiSanKhacs = new HashSet<TaiSanKhac>();
            this.KhoanNos = new HashSet<KhoanNo>();
            this.TaiSanNuocNgoais = new HashSet<TaiSanNuocNgoai>();
            this.ThuNhaps = new HashSet<ThuNhap>();
            this.GiaiTrinhs = new HashSet<GiaiTrinh>();
        }
    
        public int KKID { get; set; }
        public int KKNam { get; set; }
        public Nullable<System.DateTime> KKNgayKeKhai { get; set; }
        public Nullable<System.DateTime> KKNgayNhap { get; set; }
        public int NVID { get; set; }
        public string KKChucVu { get; set; }
        public string KKCoQuan { get; set; }
        public string KKHoKhau { get; set; }
        public string KKChoO { get; set; }
        public string KKVoChong { get; set; }
        public Nullable<System.DateTime> KKVCDOB { get; set; }
        public string KKVCChucVu { get; set; }
        public string KKVCCoQuan { get; set; }
        public string KKVCHoKhau { get; set; }
        public string KKVCChoO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nha> Nhas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeKhaiCon> KeKhaiCons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dat> Dats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tien> Tiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DongSan> DongSans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaQui> DaQuis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiSanKhac> TaiSanKhacs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhoanNo> KhoanNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiSanNuocNgoai> TaiSanNuocNgoais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuNhap> ThuNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaiTrinh> GiaiTrinhs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
