//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeKhaiCon
    {
        public int KKCID { get; set; }
        public int KKID { get; set; }
        public string KKCTen { get; set; }
        public System.DateTime KKCDOB { get; set; }
        public string KKCHoKhau { get; set; }
        public string KKCChoO { get; set; }
    
        public virtual KeKhai KeKhai { get; set; }
    }
}
