//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LamViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LamViec()
        {
            this.ChamCongs = new HashSet<ChamCong>();
            this.LamViecs1 = new HashSet<LamViec>();
        }
    
        public int LVID { get; set; }
        public int DVID { get; set; }
        public int NVID { get; set; }
        public System.DateTime LVTuNgay { get; set; }
        public Nullable<System.DateTime> LVDenNgay { get; set; }
        public int CVID { get; set; }
        public string LVNhiemVu { get; set; }
        public decimal LVPhuCapChucVu { get; set; }
        public decimal LVPhuCapCongVu { get; set; }
        public decimal LVPhuCapKiemNhiem { get; set; }
        public decimal LVPhuCapNghe { get; set; }
        public decimal LVPhuCapThamNienNghe { get; set; }
        public decimal LVPhuCapVuotKhung { get; set; }
        public decimal LVPhuCapDocHai { get; set; }
        public decimal LVLuongCoBan { get; set; }
        public decimal LVTyLe { get; set; }
        public Nullable<int> LVThuoc { get; set; }
        public int LVSoNgayPhep { get; set; }
        public string LVSoHopDong { get; set; }
        public Nullable<System.DateTime> LVNgayHopDong { get; set; }
        public int HSLID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamCong> ChamCongs { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual DonVi DonVi { get; set; }
        public virtual HeSoLuong HeSoLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LamViec> LamViecs1 { get; set; }
        public virtual LamViec LamViec1 { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
