//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nha
    {
        public int NHAID { get; set; }
        public string NHADiaChi { get; set; }
        public string NHALoai { get; set; }
        public string NHACap { get; set; }
        public decimal NHADienTich { get; set; }
        public decimal NHAGiaTri { get; set; }
        public string NHAQuyenSoHuu { get; set; }
        public string NHAGhiChu { get; set; }
        public int KKID { get; set; }
        public bool NHAIsNha { get; set; }
    
        public virtual KeKhai KeKhai { get; set; }
    }
}
