//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.Accounts = new HashSet<Account>();
            this.ChinhSaches = new HashSet<ChinhSach>();
            this.DanhGiaDangViens = new HashSet<DanhGiaDangVien>();
            this.DanhGiaLaoDongs = new HashSet<DanhGiaLaoDong>();
            this.DanhGias = new HashSet<DanhGia>();
            this.DanhGiaVienChucs = new HashSet<DanhGiaVienChuc>();
            this.KeKhais = new HashSet<KeKhai>();
            this.KhenThuongs = new HashSet<KhenThuong>();
            this.KyLuats = new HashSet<KyLuat>();
            this.PhongTangDanhHieux = new HashSet<PhongTangDanhHieu>();
            this.QuanHes = new HashSet<QuanHe>();
            this.QuaTrinhDaoTaos = new HashSet<QuaTrinhDaoTao>();
            this.ThamGiaChinhTriXaHois = new HashSet<ThamGiaChinhTriXaHois>();
            this.TrinhDoNgoaiNgus = new HashSet<TrinhDoNgoaiNgu>();
            this.TrinhDoTinHocs = new HashSet<TrinhDoTinHoc>();
            this.LamViecs = new HashSet<LamViec>();
        }
    
        public int NVID { get; set; }
        public string NVTen { get; set; }
        public string NVTenKhac { get; set; }
        public System.DateTime NVNgaySinh { get; set; }
        public int DTID { get; set; }
        public int TGID { get; set; }
        public string NVHoKhau { get; set; }
        public string NVNoiO { get; set; }
        public int GDPTID { get; set; }
        public int CMID { get; set; }
        public int LLCTID { get; set; }
        public int QLNNID { get; set; }
        public string NVSoTruong { get; set; }
        public string NVTinhTrangSucKhoe { get; set; }
        public Nullable<decimal> NVChieuCao { get; set; }
        public Nullable<decimal> NVCanNang { get; set; }
        public int NMID { get; set; }
        public string NVCMND { get; set; }
        public Nullable<System.DateTime> NVNgayCapCMND { get; set; }
        public string NVHinh { get; set; }
        public bool NVGioiTinh { get; set; }
        public string NVQueQuan { get; set; }
        public string NVNoiSinh { get; set; }
        public string NVNganh { get; set; }
        public string NVBHXH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChinhSach> ChinhSaches { get; set; }
        public virtual ChuyenMon ChuyenMon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaDangVien> DanhGiaDangViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaLaoDong> DanhGiaLaoDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaVienChuc> DanhGiaVienChucs { get; set; }
        public virtual DanToc DanToc { get; set; }
        public virtual GiaoDucPhoThong GiaoDucPhoThong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KeKhai> KeKhais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhenThuong> KhenThuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KyLuat> KyLuats { get; set; }
        public virtual LyLuanChinhTri LyLuanChinhTri { get; set; }
        public virtual NhomMau NhomMau { get; set; }
        public virtual QuanLyNhaNuoc QuanLyNhaNuoc { get; set; }
        public virtual TonGiao TonGiao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhongTangDanhHieu> PhongTangDanhHieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanHe> QuanHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhDaoTao> QuaTrinhDaoTaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThamGiaChinhTriXaHois> ThamGiaChinhTriXaHois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrinhDoNgoaiNgu> TrinhDoNgoaiNgus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrinhDoTinHoc> TrinhDoTinHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LamViec> LamViecs { get; set; }
    }
}
