//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuTrachChamCong
    {
        public int PTCCID { get; set; }
        public int ACCID { get; set; }
        public int DVID { get; set; }
        public bool PCCCStatus { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual DonVi DonVi { get; set; }
    }
}
