//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanHe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuanHe()
        {
            this.QuanHeCongTacs = new HashSet<QuanHeCongTac>();
        }
    
        public int QHID { get; set; }
        public bool QHBenVo { get; set; }
        public string QHTen { get; set; }
        public System.DateTime QHNgaySinh { get; set; }
        public bool QHGioiTinh { get; set; }
        public string QHHoKhau { get; set; }
        public string QHNoiO { get; set; }
        public int NVID { get; set; }
        public int LQHID { get; set; }
    
        public virtual LoaiQuanHe LoaiQuanHe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuanHeCongTac> QuanHeCongTacs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
