//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanHeCongTac
    {
        public int QHCTID { get; set; }
        public Nullable<System.DateTime> QHCTTuNgay { get; set; }
        public Nullable<System.DateTime> QHCTDenNgay { get; set; }
        public string QHCTDonVi { get; set; }
        public string QHCTChucVu { get; set; }
        public string QHCTNgheNghiep { get; set; }
        public string QHCTNoiDung { get; set; }
        public int QHID { get; set; }
    
        public virtual QuanHe QuanHe { get; set; }
    }
}
