//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhDaoTao
    {
        public int QTDTID { get; set; }
        public string QTDTTruong { get; set; }
        public string QTDTChuyenNganh { get; set; }
        public System.DateTime QTDTTuNgay { get; set; }
        public System.DateTime QTDTDenNgay { get; set; }
        public string QTDTHinhThuc { get; set; }
        public string QTDTVanBang { get; set; }
        public int NVID { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
