//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamGiaChinhTriXaHois
    {
        public int TGCTXHID { get; set; }
        public int NVID { get; set; }
        public int CTXHID { get; set; }
        public System.DateTime TGCTXHTuNgay { get; set; }
        public Nullable<System.DateTime> TGCTXHDenNgay { get; set; }
        public string TGCTXHChucVu { get; set; }
        public string TGCTXHNoiDung { get; set; }
    
        public virtual ChinhTriXaHois ChinhTriXaHois { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
