//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuNhap
    {
        public int TNID { get; set; }
        public string TNTen { get; set; }
        public decimal TNTien { get; set; }
        public int KKID { get; set; }
    
        public virtual KeKhai KeKhai { get; set; }
    }
}
